addons:
  apt:
    packages:
    - g++-4.8
    sources:
    - ubuntu-toolchain-r-test
before_deploy: echo 'Ok! Time to deploy. Ready?'
deploy:
  api_key:
    secure: k2LoeOZHl80SOp2n5uuTJX8jStTP59bAYSzmDZcSIVauiA45h0MbL4jfqsXc5Plx6vQVKN06lRroPL76LRFEBiAPN7dnyow1e76RaE0ha/Vd+a7YSA+D9s1ff3TvAXkt2M4fgNXCz9+8HcRtAuaqbs5gEIvxppKbmcRXWxpC5HilUO/dnTLN6z9yjqcCcKNx1MaWPg4Ih1cGvBTTy5B9F6pzPOcKId9vtEF9Rv0akkxdYk4mMgoZjmoxH0HT3wN20PRKeDNZpgDTL3RSq0jG8QTaxM/4Qz0XarV86OitCra04XDyY2PAdwEVT0fD+A1dJv0qAY4jeFvYOrrL6NOKI+4O9XOVPP8ZixzbwPvm50IpQkz+3mdDjCJ4TH/C1As7hhKhnDYluyba/WbjrBKv2eonkPaW7jV6BSsZ8pcSica6WBvO2nIuhZVwTY9SpIEa4ytiOtOPn0llPcUpkD+iip7gwAEhaqjgYSsBxysuP4/a7KrUA1vTw5rqzlcOQyitnw6urUFMgms3sLZGWqNAZR66FFcCVYls7vknLxrSL8NZTHv5t/PfjrUVq67zVzPosw21oYRXxVvzmmUzEoN+D5zEttAZ/c4SdnZaWK7TjBkYoj2fukPp2l3L9nh0aEtoyJU/uvIWR4wT7zegQjFTU+jKJ00jBj7I+nICH6rWNUU=
  app:
    master: proyecto1avanzadas
  provider: heroku
env:
- CXX=g++-4.8
language: node_js
node_js:
- 6
script:
- npm install
- npm test
